name: 'AWS cli and kubectl for AWS EKS'
author: Lemonaid Health
description: Action for running kubectl commands to interact with EKS cluster
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'Dockerfile'
